name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  linux_and_windows_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
        sudo apt-get install gcc-mingw-w64

    - name: linux build
      run: ./build.py release
    - name: check linux product
      run: |
        file aq
        ls -l aq
    - name: archive linux product
      uses: actions/upload-artifact@v1
      with:
        name: aq-linux
        path: aq

    - name: windows build
      run: ./build.py windows release
    - name: check windows product
      run: |
        file aq.exe
        ls -l aq.exe
    - name: archive windows product
      uses: actions/upload-artifact@v1
      with:
        name: aq-windows
        path: aq.exe
        
  mac_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        brew install SDL2
    - name: build
      run: ./build.py release
    - name: check mac product
      run: |
        file aq
        ls -l aq
    - name: archive mac product
      uses: actions/upload-artifact@v1
      with:
        name: aq-mac
        path: aq
